site_name: ZJUI-MATH285 文件汇总
site_author: YSH
repo_name: MATH285 文件汇总
repo_url: https://github.com/mhqqysh1/mhqqysh1.github.io
edit_uri: edit/main/

copyright: Copyright &copy; 2025 <a href="https://github.com/mhqqysh1/mhqqysh1.github.io" target="_blank" rel="noopener noreferrer">
  mhqqysh1.github.io</a>.

markdown_extensions:
  - pymdownx.tilde
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  language: zh
  logo: assets/校徽_白.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mhqqysh1/mhqqysh1.github.io
    # - icon: material/forum
    #   link: https://www.cc98.org/topic/5802442
    # - icon: fontawesome/solid/paper-plane
    #   link: mailto:me@geniucker.com
