name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Update dir and build
        run: python3 .github/scripts/build.py

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy site --project-name=zjuintl-icicles
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
