作者：Reticence
链接：https://zhuanlan.zhihu.com/p/10936342168
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

name: Deploy MkDocs
on:
  push:
    branches: 
      - master  # 或者是 main，取决于您的默认分支名称
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build and deploy
        run: |
          poetry run mkdocs gh-deploy --force