name: Deploy MkDocs
on:
  push:
    branches: 
      - main  # 或者是 main，取决于您的默认分支名称
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Update dir and build
        run: python3 .github/scripts/build.py

      - run: mkdocs gh-deploy --force

